<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace PHProm\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PHProm.v1.objective</code>
 */
class objective extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float key = 1;</code>
     */
    protected $key = 0.0;
    /**
     * Generated from protobuf field <code>float value = 2;</code>
     */
    protected $value = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $key
     *     @type float $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float key = 1;</code>
     * @return float
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>float key = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkFloat($var);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>float value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

}

